use std::io::Write;
use std::path::Path;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let shaders_dir = Path::new(&manifest_dir).join("..").join("..").join("shaders");

    let mut archive_entries: Vec<(String, String, Vec<u32>)> = Vec::new();

    if let Ok(entries) = std::fs::read_dir(&shaders_dir) {
        for entry in entries.filter_map(|e| e.ok()) {
            let path = entry.path();
            let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("").to_lowercase();
            if !matches!(ext.as_str(), "vert" | "frag" | "comp" | "glsl") {
                continue;
            }

            let stage = match ext.as_str() {
                "vert" => naga::ShaderStage::Vertex,
                "frag" => naga::ShaderStage::Fragment,
                "comp" => naga::ShaderStage::Compute,
                _ => naga::ShaderStage::Vertex,
            };

            let source = match std::fs::read_to_string(&path) {
                Ok(s) => s,
                Err(e) => {
                    println!("cargo:warning=failed to read {}: {e}", path.display());
                    continue;
                }
            };

            let mut fe = naga::front::glsl::Frontend::default();
            let module = match fe.parse(&naga::front::glsl::Options::from(stage), &source) {
                Ok(m) => m,
                Err(e) => {
                    println!("cargo:warning=failed to parse {}: {e}", path.display());
                    continue;
                }
            };

            let info = match naga::valid::Validator::new(
                naga::valid::ValidationFlags::all(),
                naga::valid::Capabilities::all(),
            )
            .validate(&module)
            {
                Ok(i) => i,
                Err(e) => {
                    println!("cargo:warning=failed to validate {}: {e}", path.display());
                    continue;
                }
            };

            let options = naga::back::spv::Options {
                flags: naga::back::spv::WriterFlags::LABEL_VARYINGS
                    | naga::back::spv::WriterFlags::CLAMP_FRAG_DEPTH,
                ..Default::default()
            };

            let spv = match naga::back::spv::write_vec(&module, &info, &options, None) {
                Ok(v) => v,
                Err(e) => {
                    println!("cargo:warning=failed to emit SPIR-V for {}: {e}", path.display());
                    continue;
                }
            };

            let name = path.file_name().unwrap().to_str().unwrap().to_string();
            let stage_str = match stage {
                naga::ShaderStage::Vertex => "Vertex",
                naga::ShaderStage::Fragment => "Fragment",
                naga::ShaderStage::Compute => "Compute",
            };
            archive_entries.push((name, stage_str.to_string(), spv));
        }
    }

    // Generate archive Rust source
    let gen_path = Path::new(&out_dir).join("shader_archive_gen.rs");
    let mut out = std::fs::File::create(&gen_path).unwrap();

    writeln!(&mut out, "// Generated by build.rs — do not edit manually.").unwrap();
    writeln!(&mut out).unwrap();

    // Write each SPIR-V as a const slice
    for (idx, (name, _stage, spv)) in archive_entries.iter().enumerate() {
        let ident = sanitize_ident(name);
        writeln!(
            &mut out,
            "static SPIRV_{}: &[u32] = &{:?};",
            ident,
            spv
        )
        .unwrap();
    }

    writeln!(&mut out).unwrap();
    writeln!(&mut out, "pub fn lookup(name: &str) -> Option<(&'static [u32], naga::ShaderStage)> {{").unwrap();
    writeln!(&mut out, "    match name {{").unwrap();

    for (name, stage, _) in &archive_entries {
        let ident = sanitize_ident(name);
        writeln!(
            &mut out,
            "        \"{name}\" => Some((SPIRV_{ident}, naga::ShaderStage::{stage})),",
        )
        .unwrap();
    }

    writeln!(&mut out, "        _ => None,").unwrap();
    writeln!(&mut out, "    }}").unwrap();
    writeln!(&mut out, "}}").unwrap();

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", shaders_dir.display());
    for (name, _, _) in &archive_entries {
        println!("cargo:rerun-if-changed={}/{}", shaders_dir.display(), name);
    }
}

fn sanitize_ident(name: &str) -> String {
    name.replace(|c: char| !c.is_alphanumeric() && c != '_', "_")
        .replace('.', "_")
}
