use rustix_core::math::{Vec3, Aabb};
use rustix_render::mesh::Mesh;
use rustix_render::Renderer;
use rustix_animation::Skeleton;

/// Unified result of importing any supported model format.
pub struct ImportedModel {
    pub mesh: Mesh,
    pub material: MaterialInfo,
    pub skeleton: Option<Skeleton>,
    pub validation: ValidationReport,
}

/// Material extracted or synthesized from the imported model.
pub struct MaterialInfo {
    pub base_color: [f32; 3],
    pub roughness: f32,
    pub metallic: f32,
    pub ao: f32,
    pub emissive: f32,
}

impl Default for MaterialInfo {
    fn default() -> Self {
        Self {
            base_color: [0.8, 0.8, 0.8],
            roughness: 0.5,
            metallic: 0.0,
            ao: 1.0,
            emissive: 0.0,
        }
    }
}

/// Report generated by mesh validation.
#[derive(Debug, Clone)]
pub struct ValidationReport {
    pub degenerate_triangles: usize,
    pub zero_area_faces: usize,
    pub nan_vertices: usize,
    pub duplicate_vertices: usize,
    pub unreferenced_vertices: usize,
    pub bounds: Aabb,
    pub warnings: Vec<String>,
}

impl Default for ValidationReport {
    fn default() -> Self {
        Self {
            degenerate_triangles: 0,
            zero_area_faces: 0,
            nan_vertices: 0,
            duplicate_vertices: 0,
            unreferenced_vertices: 0,
            bounds: Aabb { min: Vec3::ZERO, max: Vec3::ZERO },
            warnings: Vec::new(),
        }
    }
}

/// Validate indexed vertex data and return a report.
pub fn validate_mesh(vertices: &[rustix_render::mesh::Vertex], indices: Option<&[u16]>) -> ValidationReport {
    let mut report = ValidationReport::default();
    let mut used = std::collections::HashSet::new();

    // Compute bounds and check NaN
    let mut min = Vec3::splat(f32::MAX);
    let mut max = Vec3::splat(f32::MIN);
    for (i, v) in vertices.iter().enumerate() {
        let pos = Vec3::from_array(v.position);
        if pos.is_nan() || !pos.is_finite() {
            report.nan_vertices += 1;
            report.warnings.push(format!("Vertex {i} has invalid position: {pos:?}"));
        } else {
            min = min.min(pos);
            max = max.max(pos);
        }
    }
    if min.x != f32::MAX {
        report.bounds = Aabb { min, max };
    }

    if let Some(idx) = indices {
        // Check index bounds
        for (i, &index) in idx.iter().enumerate() {
            if index as usize >= vertices.len() {
                report.warnings.push(format!("Index {i} out of bounds: {index} >= {}", vertices.len()));
            } else {
                used.insert(index as usize);
            }
        }

        // Check triangles
        for tri in idx.chunks_exact(3) {
            let i0 = tri[0] as usize;
            let i1 = tri[1] as usize;
            let i2 = tri[2] as usize;
            if i0 >= vertices.len() || i1 >= vertices.len() || i2 >= vertices.len() {
                continue;
            }
            if i0 == i1 || i1 == i2 || i2 == i0 {
                report.degenerate_triangles += 1;
                continue;
            }
            let p0 = Vec3::from_array(vertices[i0].position);
            let p1 = Vec3::from_array(vertices[i1].position);
            let p2 = Vec3::from_array(vertices[i2].position);
            let area = (p1 - p0).cross(p2 - p0).length() * 0.5;
            if area < 1e-8 {
                report.zero_area_faces += 1;
            }
        }
    } else {
        // Non-indexed: every 3 vertices is a triangle
        for tri in vertices.chunks_exact(3) {
            let p0 = Vec3::from_array(tri[0].position);
            let p1 = Vec3::from_array(tri[1].position);
            let p2 = Vec3::from_array(tri[2].position);
            let area = (p1 - p0).cross(p2 - p0).length() * 0.5;
            if area < 1e-8 {
                report.zero_area_faces += 1;
            }
            used.insert(0); // All vertices are implicitly used
        }
    }

    if !used.is_empty() {
        report.unreferenced_vertices = vertices.len().saturating_sub(used.len());
        if report.unreferenced_vertices > 0 {
            report.warnings.push(format!("{} unreferenced vertices", report.unreferenced_vertices));
        }
    }

    if report.degenerate_triangles > 0 {
        report.warnings.push(format!("{} degenerate triangles", report.degenerate_triangles));
    }
    if report.zero_area_faces > 0 {
        report.warnings.push(format!("{} zero-area faces", report.zero_area_faces));
    }

    report
}

/// Build an ImportedModel from raw vertex/index data with validation.
pub fn build_imported_model(
    renderer: &Renderer,
    name: &str,
    vertices: &[rustix_render::mesh::Vertex],
    indices: Option<(&[u16], u32)>,
    material: MaterialInfo,
    skeleton: Option<Skeleton>,
) -> Result<ImportedModel, String> {
    let idx_slice = indices.as_ref().map(|(i, _)| &i[..]);
    let validation = validate_mesh(vertices, idx_slice);

    let ibuf = indices.map(|(data, count)| (&data[..], count));
    let mesh = Mesh::new(renderer, name, bytemuck::cast_slice(vertices), vertices.len() as u32, ibuf)
        .map_err(|e| format!("mesh upload: {e}"))?;

    Ok(ImportedModel {
        mesh,
        material,
        skeleton,
        validation,
    })
}

/// Unified entry point: dispatch to the correct loader by file extension.
pub fn import_model(renderer: &Renderer, data: &[u8], name: &str, ext: &str) -> Result<ImportedModel, String> {
    match ext.to_lowercase().as_str() {
        "obj" => crate::obj_loader::load_obj(renderer, data, name),
        "glb" | "gltf" => crate::gltf_loader::load_glb(renderer, data, name),
        _ => Err(format!("unsupported model format: {ext}")),
    }
}
